# remap prefix to C-a
unbind C-b
set -g prefix C-a
bind a send-prefix

# force a reload of the config files.
unbind r
bind r source-file ~/.tmux.conf

# Screen like bindings.
# quick pane cycling
unbind ^A
bind ^a select-pane -t :.+

# Rebind split keys.
unbind %
bind | split-window -h -c "#{pane_current_path}"
unbind '"'
bind S split-window -v -c "#{pane_current_path}"
bind _ split-window -v -c "#{pane_current_path}"
bind '"' choose-window
# rebind kill key
bind K confirm-before 'kill-window'

bind-key -r '+' resize-pane -U 10
bind-key -r '-' resize-pane -D 10
bind-key -r '<' resize-pane -L 10
bind-key -r '>' resize-pane -R 10

# status bar cusomtizations.
set -g base-index 1
set -g status-position top
set -g renumber-windows on
set -g display-time 3000
set -g status-bg "#210203"
set -g status-fg "#6D98BA"

set-option -sg escape-time 10
set-option -g focus-events on
set-option -g default-terminal "tmux-256color"

#dark colours
set-window-option -g window-status-current-bg black
set-window-option -g window-status-current-fg yellow
set-window-option -g window-status-current-attr bright
set -g window-style 'fg=colour247,bg=colour236'
set -g window-active-style 'fg=colour250,bg=black'

set -g status-right '#[fg=#C17767]%l:%M:%S %p %a %d-%b-%y'
setw -g automatic-rename off
set status-interval 2

# vim like bindings.
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# use vim motion keys while in copy mode.
setw -g mode-keys vi

# scrollback buffer n lines.
set -g history-limit 100000

# command/message line colors
set -g message-fg white
set -g message-bg black
set -g message-attr bright

# resize panes like vim
bind < resize-pane -L 10
bind > resize-pane -R 10
bind - resize-pane -D 10
bind + resize-pane -U 10

## fix the titles.
set -g set-titles on
set -g set-titles-string "#H:#S.#I.#P :#W #T"

# set -g default-terminal "${TERM}"

# Sane scrolling
set -g mouse on
setw -g alternate-screen on

# Integration with neovim
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?\.?(view|n?vim?x?)(-wrapped)?(diff)?$'"

bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h' { if -F '#{pane_at_left}' '' 'select-pane -L' }
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j' { if -F '#{pane_at_bottom}' '' 'select-pane -D' }
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k' { if -F '#{pane_at_top}' '' 'select-pane -U' }
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l' { if -F '#{pane_at_right}' '' 'select-pane -R' }

bind-key -T copy-mode-vi 'C-h' if -F '#{pane_at_left}' '' 'select-pane -L'
bind-key -T copy-mode-vi 'C-j' if -F '#{pane_at_bottom}' '' 'select-pane -D'
bind-key -T copy-mode-vi 'C-k' if -F '#{pane_at_top}' '' 'select-pane -U'
bind-key -T copy-mode-vi 'C-l' if -F '#{pane_at_right}' '' 'select-pane -R'
